poi:
  submap_0:
    poi_1: [submap_0, kitchen, 5.126, 8, -0.078]
    poi_2: [submap_0, charger, 6.842, 11.315, -3.037]
    poi_3: [submap_0, software, 5.670, 4.938, 2.924]
    poi_4: [submap_0, business, 1.878, 3.067, 1.047]
    poi_5: [submap_0, meetingTable, 4.081, -2.811, 0.0]
    poi_6: [submap_0, exit, -0.820, -10.496, -1.643]
    poi_7: [submap_0, people, -4.596, 28.905, -0.349]
locations_prob: # Locations and its probabilities of having objects on top
    # Syntax: Name_of_room/location_in_room: [probabolity, pos.x, pos.y, angle]
    living:
        table:      [0.90, 1.878, 3.067, 1.047]
        chair:      [0.65, 1.878, 3.067, 1.047]
        sofa:       [0.40, 1.878, 3.067, 1.047]
        tv:         [0.05, 1.878, 3.067, 1.047]
        shelf:      [0.70, 1.878, 3.067, 1.047]
        floor:      [0.30, 1.878, 3.067, 1.047]

    bedroom:
        desk:       [0.85, 6.842, 11.315, -3.037]
        chair:      [0.70, 6.842, 11.315, -3.037]
        shelf:      [0.80, 6.842, 11.315, -3.037]
        nightstand: [0.75, 6.842, 11.315, -3.037]
        floor:      [0.40, 6.842, 11.315, -3.037]
        table:      [0.90, 6.842, 11.315, -3.037]
        bed:        [0.56, 6.842, 11.315, -3.037]

    kitchen:
        countertop: [0.80, 5.126, 7.000, -0.078]
        table:      [0.95, 5.126, 8.000, -0.078]
        shelf:      [0.50, 5.126, 7.500, -0.078]
        dishwasher: [0.20, 5.126, 5.000, -0.078]
        floor:      [0.10, 5.126, 8.200, -0.078]
vo:
  submap_0:
    virtualObstacles_1: [submap_0, VO1, 6.039, -3.835,  0.8]
    virtualObstacles_2: [submap_0, VO1, 0.304, -3.889,  0.8]
    virtualObstacles_3: [submap_0, VO1, -0.068, -10.640, 0.8]
    virtualObstacles_4: [submap_0, VO2, 3.338, 1.196, 0.8]
    virtualObstacles_5: [submap_0, VO2, 5.010, -0.376, 0.8]
    virtualObstacles_6: [submap_0, VO2, 5.811, 2.893, 0.8]
    virtualObstacles_7: [submap_0, VO2, 1.850, 3.368, 0.8]

